"""Example 02: Run forward tomography

This script uses the parameter file generated by
`examples/01_generate_spot_data.py` (located at `input/params_tomog.txt`)
to run the pyZeeTom forward tomography pipeline.

How to run (from project root)::

	python examples/02_forward_tomography.py

After running you will get:

- `output/forward_test/` containing per-phase `.tomog` models
- Corresponding model spectra written by the tomography engine
"""

from __future__ import annotations

import os
import sys
from pathlib import Path

# Ensure project root (parent of examples) is on sys.path so that
# `pyzeetom`, `core`, and `utils` can be imported when running this
# script directly.
project_root = Path(__file__).resolve().parent.parent
if str(project_root) not in sys.path:
    sys.path.insert(0, str(project_root))
os.environ["PYTHONPATH"] = str(project_root)

from pyzeetom import tomography


def get_project_root() -> Path:
    return project_root


def main() -> None:
    project_root = get_project_root()
    param_file = project_root / "input" / "params_tomog.txt"

    if not param_file.exists():
        raise FileNotFoundError(
            f"Parameter file not found: {param_file}. "
            "Please run examples/01_generate_spot_data.py first.")

    output_dir = project_root / "output" / "forward_test"
    output_dir.mkdir(parents=True, exist_ok=True)

    print("Running forward tomography...")
    forward_results = tomography.forward_tomography(
        param_file=str(param_file),
        verbose=1,
        output_dir=str(output_dir),
    )

    print(f"Forward tomography finished, {len(forward_results)} phases.")


if __name__ == "__main__":
    main()
