"""Example 03: Run MEM inversion tomography

This script uses the synthetic spectra generated by
`examples/02_forward_tomography.py` (based on `input/params_tomog.txt`)
and runs the pyZeeTom Maximum Entropy Method (MEM) inversion pipeline.

How to run (from project root)::

	python examples/03_inversion_tomography.py

After running you will get:

- `output/inverse_test/` containing MEM inversion products
- Especially `mem_inversion_model.tomog` as the final reconstructed model
"""

from __future__ import annotations

import os
import sys
from pathlib import Path

# Ensure project root (parent of examples) is on sys.path so that
# `pyzeetom`, `core`, and `utils` can be imported when running this
# script directly.
project_root = Path(__file__).resolve().parent.parent
if str(project_root) not in sys.path:
    sys.path.insert(0, str(project_root))
os.environ["PYTHONPATH"] = str(project_root)

from pyzeetom import tomography
from core import SpecIO
import numpy as np


def get_project_root() -> Path:
    return project_root


def main() -> None:
    project_root = get_project_root()
    param_file = project_root / "input" / "params_tomog.txt"

    if not param_file.exists():
        raise FileNotFoundError(
            f"Parameter file not found: {param_file}. "
            "Please run examples/01_generate_spot_data.py first.")

    # Forward synthetic spectra directory (produced by example 02)
    forward_dir = project_root / "output" / "forward_test"
    if not forward_dir.exists():
        raise FileNotFoundError(
            f"Forward results not found: {forward_dir}. "
            "Please run examples/02_forward_tomography.py first.")

    # Directory where we will write noisy spectra for inversion
    output_dir = project_root / "output" / "inverse_test"
    output_dir.mkdir(parents=True, exist_ok=True)

    # ------------------------------------------------------------------
    # 1) Take forward-model spectra and add Gaussian noise
    # ------------------------------------------------------------------
    print("Preparing noisy observed spectra from forward results...")

    # 精确使用 forward_test 中的 .spec 文件
    import glob

    spec_files = sorted(glob.glob(str(forward_dir / "phase_*.spec")))

    if not spec_files:
        raise FileNotFoundError(
            f"No forward spectra found under {forward_dir}. "
            "Check output of examples/02_forward_tomography.py.")

    snr = 1000.0  # you can adjust S/N here
    sigma = 1.0 / snr
    np.random.seed(42)

    noisy_obs_dir = project_root / "input" / "spot_forward_obs"
    noisy_obs_dir.mkdir(parents=True, exist_ok=True)

    noisy_files = []
    for fpath in spec_files:
        obs = SpecIO.loadObsProfile(fpath)
        if obs is None:
            continue

        rv = obs.wl
        spec_i = obs.specI
        spec_v = getattr(obs, "specV", None)
        spec_q = getattr(obs, "specQ", None)
        spec_u = getattr(obs, "specU", None)

        noise_I = np.random.normal(0, sigma, spec_i.shape)
        new_I = spec_i + noise_I

        kwargs = {}
        if spec_v is not None:
            noise_V = np.random.normal(0, sigma, spec_v.shape)
            kwargs["V"] = spec_v + noise_V
        if spec_q is not None:
            noise_Q = np.random.normal(0, sigma, spec_q.shape)
            kwargs["Q"] = spec_q + noise_Q
        if spec_u is not None:
            noise_U = np.random.normal(0, sigma, spec_u.shape)
            kwargs["U"] = spec_u + noise_U

        new_sig = np.ones_like(spec_i) * sigma

        # 文件名与 params_tomog.txt 中完全一致：obs_phase_{phase:.3f}.lsd
        stem = Path(fpath).stem  # e.g. phase_0000_HJD2450000p000_VRp0p00_V
        # 前 4 位索引转成相位列表里的值
        idx = int(stem.split("_")[1])  # 0000 -> 0, 0001 -> 1, ...
        phases = np.array([
            0.0,
            0.05,
            0.12,
            0.18,
            0.25,
            0.33,
            0.41,
            0.48,
            0.55,
            0.65,
            0.72,
            0.80,
            0.88,
            0.92,
            0.98,
        ])
        phase = phases[idx]
        out_path = noisy_obs_dir / f"obs_phase_{phase:.3f}.lsd"

        SpecIO.write_model_spectrum(
            filename=str(out_path),
            x=rv,
            Iprof=new_I,
            sigmaI=new_sig,
            fmt="lsd",
            pol_channel="V",
            file_type_hint="lsd_pol",
            **kwargs,
        )

        noisy_files.append(str(out_path))

    if not noisy_files:
        raise RuntimeError("Failed to create any noisy observation spectra.")

    print("Running inversion...")
    inverse_results = tomography.inversion_tomography(
        param_file=str(param_file),
        verbose=1,
        output_dir=str(output_dir),
    )

    final = inverse_results[-1]
    print(f"Inversion complete. Final chi^2 = {final.final_chi2:.3f}")


if __name__ == "__main__":
    main()
